@echo off
echo Initializing Git repository...
git init
echo Adding files...
git add .
echo Committing files...
git commit -m "Initial commit of Eloquente Catering App"
echo Renaming branch to main...
git branch -M main
echo Setting remote origin...
git remote remove origin
git remote add origin https://github.com/mavvricks/eloque
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
